### ISSUE TITLE
[Issue] https://eve-kill.com/api/characters/ times out fetching data

### ISSUE THREAD

**Issue by OrangeDrangon** [EVE-KILL/Issues#27]
**Describe the bug**
When attempting to query https://eve-kill.com/api/characters/ the request times out with error code 524

**To Reproduce**
1. curl --request GET \
          --url https://eve-kill.com/api/characters/
2. Wait 100 seconds

**Expected behavior**
Return the data probably across multiple requests.

**Screenshots**
![image](https://github.com/user-attachments/assets/6ebf6523-709c-4406-99c9-037b804b6337)

**Platform**
 - API

**Additional context**
I think it would make sense to add a page query param ie `?page=x`. Returning 20e6 characters in one request seems optimistic.

**Comment by karbowiak** [comment]
Fixed https://github.com/EVE-KILL/Killboard/commit/b3204511a315f52d54f50d5c6e26918d0d028366

I added pagination to it that emits 10k at a time.

https://eve-kill.com/api/characters for the first 10k (it's basically the same as https://eve-kill.com/api/characters/page/1)
And after that you just increment the page number until you get under 10k.

If you want a backfill there is one available on everef as well https://data.everef.net/characters-corporations-alliances/backfills/

It's a few weeks old at this point, but i havn't gotten _THAT_ many characters since then.
As for the total amount of pages, if you hit up the https://eve-kill.com/api/characters/count API first, then divide the result by 10000 you get the total page number.

I also sorted the output by character_id in ascending (so starts low, and goes high) meaning you can easier work your way backwards to ensure that your tool is up-to-date with the latest data :)

Hope this solves it, otherwise let me know and i'll reopen and fix
